# Generated by Django 5.2.6 on 2025-09-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_saletransaction_saleitem_stockentry_stockentryitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='saleitem',
            table='sale_items',
        ),
        migrations.AlterModelTable(
            name='saletransaction',
            table='sale_transactions',
        ),
        migrations.AlterModelTable(
            name='stockentryitem',
            table='stock_enrty_items',
        ),
    ]
